# Generated by Django 2.0.4 on 2018-06-09 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_allowed', models.BooleanField(default=False)),
                ('login_required', models.BooleanField(default=False)),
                ('history_recored', models.BooleanField(default=True)),
            ],
        ),
    ]
