# Generated by Django 2.0.4 on 2018-06-09 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apientry',
            name='created_by',
            field=models.CharField(blank=True, editable=False, max_length=30),
        ),
        migrations.AlterField(
            model_name='apientry',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='apientry',
            name='updated_by',
            field=models.CharField(blank=True, editable=False, max_length=30),
        ),
        migrations.AlterField(
            model_name='apirequest',
            name='created_by',
            field=models.CharField(blank=True, editable=False, max_length=30),
        ),
        migrations.AlterField(
            model_name='apirequest',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='apirequest',
            name='updated_by',
            field=models.CharField(blank=True, editable=False, max_length=30),
        ),
        migrations.AlterField(
            model_name='apirequestfield',
            name='created_by',
            field=models.CharField(blank=True, editable=False, max_length=30),
        ),
        migrations.AlterField(
            model_name='apirequestfield',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='apirequestfield',
            name='updated_by',
            field=models.CharField(blank=True, editable=False, max_length=30),
        ),
        migrations.AlterField(
            model_name='apiresponse',
            name='created_by',
            field=models.CharField(blank=True, editable=False, max_length=30),
        ),
        migrations.AlterField(
            model_name='apiresponse',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='apiresponse',
            name='updated_by',
            field=models.CharField(blank=True, editable=False, max_length=30),
        ),
        migrations.AlterField(
            model_name='apiresponsefield',
            name='created_by',
            field=models.CharField(blank=True, editable=False, max_length=30),
        ),
        migrations.AlterField(
            model_name='apiresponsefield',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='apiresponsefield',
            name='updated_by',
            field=models.CharField(blank=True, editable=False, max_length=30),
        ),
        migrations.AlterField(
            model_name='dataobject',
            name='created_by',
            field=models.CharField(blank=True, editable=False, max_length=30),
        ),
        migrations.AlterField(
            model_name='dataobject',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='dataobject',
            name='updated_by',
            field=models.CharField(blank=True, editable=False, max_length=30),
        ),
        migrations.AlterField(
            model_name='fieldtemplate',
            name='created_by',
            field=models.CharField(blank=True, editable=False, max_length=30),
        ),
        migrations.AlterField(
            model_name='fieldtemplate',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='fieldtemplate',
            name='updated_by',
            field=models.CharField(blank=True, editable=False, max_length=30),
        ),
        migrations.AlterField(
            model_name='group',
            name='created_by',
            field=models.CharField(blank=True, editable=False, max_length=30),
        ),
        migrations.AlterField(
            model_name='group',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='describe',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='group',
            name='updated_by',
            field=models.CharField(blank=True, editable=False, max_length=30),
        ),
        migrations.AlterField(
            model_name='module',
            name='created_by',
            field=models.CharField(blank=True, editable=False, max_length=30),
        ),
        migrations.AlterField(
            model_name='module',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='updated_by',
            field=models.CharField(blank=True, editable=False, max_length=30),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_by',
            field=models.CharField(blank=True, editable=False, max_length=30),
        ),
        migrations.AlterField(
            model_name='project',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='describe',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='project',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.Group'),
        ),
        migrations.AlterField(
            model_name='project',
            name='updated_by',
            field=models.CharField(blank=True, editable=False, max_length=30),
        ),
    ]
