# Generated by Django 2.0.4 on 2018-06-09 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20180609_0628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='base_url',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='module',
            name='describe',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
    ]
