# Generated by Django 2.0.5 on 2018-06-25 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='status',
        ),
        migrations.AddField(
            model_name='project',
            name='scope',
            field=models.CharField(choices=[('public', 'public'), ('private', 'private')], default='public', max_length=30),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('maintaining', 'maintaining'), ('deprecated', 'deprecated'), ('disabled', 'disabled')], default='maintaining', max_length=30),
        ),
        migrations.AlterField(
            model_name='group',
            name='scope',
            field=models.CharField(choices=[('public', 'public'), ('private', 'private')], default='public', max_length=30),
        ),
    ]
