# Generated by Django 2.0.5 on 2018-06-28 04:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0002_auto_20180625_0549'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='favorite',
            field=models.ManyToManyField(related_name='group_favorites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='group',
            name='manager',
            field=models.ManyToManyField(related_name='group_managers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='group',
            name='reader',
            field=models.ManyToManyField(related_name='group_readers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='favorite',
            field=models.ManyToManyField(related_name='project_favorites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='manager',
            field=models.ManyToManyField(related_name='project_managers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='reader',
            field=models.ManyToManyField(related_name='project_readers', to=settings.AUTH_USER_MODEL),
        ),
    ]
