# Generated by Django 2.0.4 on 2018-06-30 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20180628_0711'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GlobaConfig',
            new_name='GlobalConfig',
        ),
    ]
