# Generated by Django 2.0.4 on 2018-06-30 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20180630_0628'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalconfig',
            name='allow_register',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='globalconfig',
            name='need_login',
            field=models.BooleanField(default=True),
        ),
    ]
