# Generated by Django 2.0.5 on 2018-07-03 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_userextra'),
    ]

    operations = [
        migrations.AddField(
            model_name='apientry',
            name='describe',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
    ]
