# Generated by Django 2.0.5 on 2018-07-03 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_apientry_describe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='base_url',
            new_name='prefix',
        ),
    ]
