# Generated by Django 2.0.5 on 2018-07-03 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_auto_20180703_0651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='describe',
        ),
        migrations.AddField(
            model_name='module',
            name='deprecated',
            field=models.BooleanField(default=False),
        ),
    ]
