# Generated by Django 2.0.5 on 2018-07-09 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_auto_20180703_1105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='deprecated',
        ),
    ]
