# Generated by Django 2.0.5 on 2018-07-09 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_remove_module_deprecated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='globalconfig',
            old_name='base_url',
            new_name='mount_url',
        ),
    ]
