# Generated by Django 2.0.5 on 2018-07-09 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_auto_20180709_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalconfig',
            name='mount_url',
            field=models.CharField(blank=True, default='/apibook', max_length=100, null=True),
        ),
    ]
