# Generated by Django 2.0.5 on 2018-07-09 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_auto_20180709_0850'),
    ]

    operations = [
        migrations.RenameField(
            model_name='globalconfig',
            old_name='need_login',
            new_name='freelance',
        ),
    ]
